version: '3.9'

services:
  mysqlservice:
    image: mysql:latest
    container_name: mysqlservice
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myplusdb
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql-scripts:/docker-entrypoint-initdb.d
  myplus:
    build:
      context: .
      dockerfile: Dockerfile
    image: myplus
    container_name: myplus
    depends_on:
      - mysqlservice
    ports:
      - "8080:8080"
