version: '3.7'
services:
  myplus-db:
    container_name: myplus-db
    image: mysql:latest
    networks:
      - myplus-network
    environment:
      - spring.datasource.url=jdbc:mysql://myplusdb:3306/basics?allowPublicKeyRetrieval=true 
      # - MYSQL_USER=root
      # - MYSQL_PASSWORD=root
      # - MYSQL_DATABASE=myplusdb
      # - MYSQL_ROOT_PASSWORD=root
    volumes:
      - dbvol:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always

  myplus-app:
    build:
      context: .
    container_name: myplus-spring
    image: shahidhussainabbasi/myplusrepo:latest
    ports:
      - "8080:8080"
    networks:
      - myplus-network
    depends_on:
      - myplus-db
    environment:
      - MYSQL_HOST=myplus-db
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=myplusdb
      - MYSQL_PORT=3306

networks:
  myplus-network:
    name: myplus-network

volumes:
  dbvol: