package com.myplus.clinical.entity;

import java.time.LocalDate;
import java.time.LocalDateTime;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.Version;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * HMS S2 — one patient's place in one doctor's line for one day (V2). Status changes never go through a
 * load-modify-save: each is one conditional UPDATE in {@code QueueTokenRepo}, so two desks or two doctors acting
 * at once cannot both win. {@link #livePatientId} is a database-generated column, read-only here.
 */
@Entity
@Table(name = "queue_token")
@Getter @Setter @NoArgsConstructor
public class QueueToken {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "organization_id", nullable = false)
    private Long organizationId;

    @Column(name = "patient_id", nullable = false)
    private Long patientId;

    @Column(name = "provider_id", nullable = false)
    private Long providerId;

    /** The doctor's name when the token was issued — the board never calls appointment-service per row. */
    @Column(name = "provider_name", length = 120)
    private String providerName;

    @Column(name = "visit_date", nullable = false)
    private LocalDate visitDate;

    @Column(name = "token_no", nullable = false)
    private Integer tokenNo;

    /** A-007: the doctor's letter and the number. */
    @Column(name = "token_label", nullable = false, length = 16)
    private String tokenLabel;

    @Column(name = "status", nullable = false, length = 20)
    private String status = QueueStatus.WAITING;

    /** Generated by MySQL: the patient while live, NULL once CANCELLED / NO_SHOW (uq_token_live). */
    @Column(name = "live_patient_id", insertable = false, updatable = false)
    private Long livePatientId;

    @Column(name = "park_reason", length = 255)
    private String parkReason;

    @Column(name = "cancel_reason", length = 255)
    private String cancelReason;

    @Column(name = "called_by")
    private Long calledBy;

    @Column(name = "called_at")
    private LocalDateTime calledAt;

    @Column(name = "started_at")
    private LocalDateTime startedAt;

    @Column(name = "parked_at")
    private LocalDateTime parkedAt;

    @Column(name = "completed_at")
    private LocalDateTime completedAt;

    @Column(name = "cancelled_at")
    private LocalDateTime cancelledAt;

    @Column(name = "created_by")
    private Long createdBy;

    @Column(name = "created_at")
    private LocalDateTime createdAt;

    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    @Version
    @Column(name = "version", nullable = false)
    private Long version = 0L;
}
