server:
  port: 8089

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/myplusdb_campaign?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&connectionTimeZone=%2B05:00&forceConnectionTimeZoneToSession=true
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USER:noreply@myplus.com}
    password: ${MAIL_PASSWORD:changeme}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
