server:
  port: 8093

spring:
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:465}
    protocol: ${MAIL_PROTOCOL:smtps}
    username: ${MAIL_USER:maxtheservice@gmail.com}
    password: "${MAIL_PASSWORD:changeme}"
    properties:
      mail:
        transport:
          protocol: smtps
        smtps:
          auth: true
          starttls:
            enable: true
          timeout: 8000
