package com.myplus.business_service.entity;

import java.time.LocalDateTime;

import jakarta.persistence.*;
import lombok.*;

/**
 * SER-2 — one physically identified unit: a handset's IMEI, an appliance's serial number.
 *
 * <h3>What this replaces</h3>
 * {@code InstallmentPlan.assetRef} — free text on a finance agreement, described by its own javadoc as "a
 * LABEL, not a register". It was captured only when a handset was FINANCED, so a shop that bought ten and sold
 * three for cash recorded no IMEI at all and could not say who held any of them.
 *
 * <h3>Stock at quantity one, with identity and a lifecycle</h3>
 * A purchase creates it, a sale consumes it, a return or repossession puts it back:
 * {@code IN_STOCK → SOLD → IN_STOCK}. inventory-service still owns the QUANTITY; this owns WHICH UNIT.
 *
 * <h3>{@code live_serial_no} is a generated column and must never be written</h3>
 * The database derives it from {@link #status} (V52), and the unique index over it is what makes "the same
 * serial cannot be in stock twice" a guarantee rather than a hope. It is mapped read-only here so JPA cannot
 * try to insert it — a write would fail at the database with a message about a generated column, which reads
 * as a schema fault rather than as the mapping mistake it is.
 */
@Entity
@Table(name = "serial_unit")
@Getter @Setter @NoArgsConstructor @AllArgsConstructor @Builder
public class SerialUnit {

    /** In stock and sellable. The only status the uniqueness constraint considers. */
    public static final String IN_STOCK = "IN_STOCK";
    /** Sold and gone. Frees the serial for a future buy-back of the same unit. */
    public static final String SOLD = "SOLD";
    /** Written off. Also frees the serial — the unit is not coming back. */
    public static final String SCRAPPED = "SCRAPPED";

    /** SER-4 condition grades. NEW is the default because most trade is new stock. */
    public static final String NEW = "NEW";
    public static final String USED = "USED";
    public static final String REFURBISHED = "REFURBISHED";

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "serial_unit_id")
    private Long serialUnitId;

    @Column(name = "organization_id", nullable = false)
    private Long organizationId;

    /** Audit — who registered the unit. Kept for the same reason every other row here keeps it. */
    @Column(name = "user_id")
    private Long userId;

    /** Multi-location: the branch holding this unit. Null = single-store. */
    @Column(name = "store_id")
    private Long storeId;

    @Column(name = "product_id", nullable = false)
    private Long productId;

    /** The IMEI or serial as recorded. Trimmed and upper-cased on the way in, so lookups are predictable. */
    @Column(name = "serial_no", nullable = false, length = 64)
    private String serialNo;

    @Builder.Default
    @Column(name = "condition_grade", nullable = false, length = 16)
    private String conditionGrade = NEW;

    @Builder.Default
    @Column(name = "status", nullable = false, length = 16)
    private String status = IN_STOCK;

    /** The purchase that brought it in. */
    @Column(name = "purchase_id")
    private Long purchaseId;

    /**
     * Reserved for a per-LINE link to a {@code Sell} row. Unused today.
     *
     * <p>The sale path does not expose a line id — {@code SagaSaleWriter} returns the invoice and writes the
     * lines inside it — so {@link #invoiceNo} carries the answer instead. Storing an invoice id in a column
     * named {@code sell_id} would read correctly and mean something else, which is the kind of mismatch that
     * costs an afternoon two years later.
     */
    @Column(name = "sell_id")
    private Long sellId;

    /**
     * SER-3 — the invoice this unit left on. Null while in stock.
     *
     * <p>The invoice NUMBER rather than an id, because it is what a warranty claim, a return or a police
     * enquiry actually quotes, and it is what the shop can read off the customer's receipt.
     */
    @Column(name = "invoice_no", length = 32)
    private String invoiceNo;

    @Column(name = "dated")
    private LocalDateTime dated;

    @Column(name = "updated")
    private LocalDateTime updated;

    /**
     * Generated by the database — {@code serial_no} when IN_STOCK, otherwise NULL.
     *
     * <p>{@code insertable=false, updatable=false} is load-bearing: MySQL rejects any write to a generated
     * column, and the resulting error would point at the schema rather than at the mapping.
     */
    @Column(name = "live_serial_no", insertable = false, updatable = false, length = 64)
    private String liveSerialNo;
}
