-- Forward migration for education org-scoping (tech-debt #13; slices 01-16): add organization_id to the
-- education domain tables. IDEMPOTENT — guarded by information_schema so it's a no-op where ddl-auto
-- already added the column (dev) and correct on a fresh/prod (validate) DB. Runs after the V1 baseline.
-- NOTE: the owner per-tenant unique(organization_id, name) change (old global name unique dropped) stays
-- in docs/migrations.md #1 — index names vary per env and Hibernate validate does not check them.
SET @ddl := IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='school'         AND COLUMN_NAME='organization_id')=0, 'ALTER TABLE school ADD COLUMN organization_id BIGINT NULL', 'DO 0');         PREPARE s FROM @ddl; EXECUTE s; DEALLOCATE PREPARE s;
SET @ddl := IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='owner'          AND COLUMN_NAME='organization_id')=0, 'ALTER TABLE owner ADD COLUMN organization_id BIGINT NULL', 'DO 0');          PREPARE s FROM @ddl; EXECUTE s; DEALLOCATE PREPARE s;
SET @ddl := IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='grade'          AND COLUMN_NAME='organization_id')=0, 'ALTER TABLE grade ADD COLUMN organization_id BIGINT NULL', 'DO 0');          PREPARE s FROM @ddl; EXECUTE s; DEALLOCATE PREPARE s;
SET @ddl := IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='subject'        AND COLUMN_NAME='organization_id')=0, 'ALTER TABLE subject ADD COLUMN organization_id BIGINT NULL', 'DO 0');        PREPARE s FROM @ddl; EXECUTE s; DEALLOCATE PREPARE s;
SET @ddl := IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='staff'          AND COLUMN_NAME='organization_id')=0, 'ALTER TABLE staff ADD COLUMN organization_id BIGINT NULL', 'DO 0');          PREPARE s FROM @ddl; EXECUTE s; DEALLOCATE PREPARE s;
SET @ddl := IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='guardian'       AND COLUMN_NAME='organization_id')=0, 'ALTER TABLE guardian ADD COLUMN organization_id BIGINT NULL', 'DO 0');       PREPARE s FROM @ddl; EXECUTE s; DEALLOCATE PREPARE s;
SET @ddl := IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='student'        AND COLUMN_NAME='organization_id')=0, 'ALTER TABLE student ADD COLUMN organization_id BIGINT NULL', 'DO 0');        PREPARE s FROM @ddl; EXECUTE s; DEALLOCATE PREPARE s;
SET @ddl := IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='vehicle'        AND COLUMN_NAME='organization_id')=0, 'ALTER TABLE vehicle ADD COLUMN organization_id BIGINT NULL', 'DO 0');        PREPARE s FROM @ddl; EXECUTE s; DEALLOCATE PREPARE s;
SET @ddl := IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='discount'       AND COLUMN_NAME='organization_id')=0, 'ALTER TABLE discount ADD COLUMN organization_id BIGINT NULL', 'DO 0');       PREPARE s FROM @ddl; EXECUTE s; DEALLOCATE PREPARE s;
SET @ddl := IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='attendance'     AND COLUMN_NAME='organization_id')=0, 'ALTER TABLE attendance ADD COLUMN organization_id BIGINT NULL', 'DO 0');     PREPARE s FROM @ddl; EXECUTE s; DEALLOCATE PREPARE s;
SET @ddl := IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='fee_collection' AND COLUMN_NAME='organization_id')=0, 'ALTER TABLE fee_collection ADD COLUMN organization_id BIGINT NULL', 'DO 0'); PREPARE s FROM @ddl; EXECUTE s; DEALLOCATE PREPARE s;
SET @ddl := IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='fee_setting'    AND COLUMN_NAME='organization_id')=0, 'ALTER TABLE fee_setting ADD COLUMN organization_id BIGINT NULL', 'DO 0');    PREPARE s FROM @ddl; EXECUTE s; DEALLOCATE PREPARE s;
SET @ddl := IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='alert'          AND COLUMN_NAME='organization_id')=0, 'ALTER TABLE alert ADD COLUMN organization_id BIGINT NULL', 'DO 0');          PREPARE s FROM @ddl; EXECUTE s; DEALLOCATE PREPARE s;
SET @ddl := IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='alert_channel'  AND COLUMN_NAME='organization_id')=0, 'ALTER TABLE alert_channel ADD COLUMN organization_id BIGINT NULL', 'DO 0');  PREPARE s FROM @ddl; EXECUTE s; DEALLOCATE PREPARE s;
