#!/usr/bin/env python3
"""MKT requirement traceability matrix — COMPUTED, never typed.

Reads:
  requirements  ../marketplace-multiseller-analysis.md         rows "| MKT-Rx.y | text | phase |"
  unit          marketplace-service/src/test/.../multiseller/  @DisplayName("[MKT-Rx.y] ...")
  cypress       cypress/e2e/marketplace/*.cy.js                it('MKT-xx-nn [MKT-Rx.y] ...')
  manual        ./manual-cases.json                            "reqs": [...]
Writes the matrix between the RTM markers in ../marketplace-multiseller-test-plan.md and ./rtm.json.
Exit 1 if a requirement has no test of any kind, or a test cites an id that is not a requirement (a typo would
otherwise count as coverage).

Run from the repo root or anywhere:  python3 microservices/docs/marketplace/rtm.py
"""
import json, pathlib, re, sys

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parents[2]
ANALYSIS = HERE.parent / 'marketplace-multiseller-analysis.md'
PLAN = HERE.parent / 'marketplace-multiseller-test-plan.md'
UNIT = ROOT / 'microservices/marketplace-service/src/test/java/com/myplus/marketplace/multiseller'
CY = ROOT / 'cypress/e2e/marketplace'
ID = re.compile(r'MKT-R\d+\.\d+')

reqs = {}
for line in ANALYSIS.read_text(encoding='utf-8').splitlines():
    m = re.match(r'\|\s*(MKT-R\d+\.\d+)\s*\|\s*(.+?)\s*\|\s*([^|]+?)\s*\|\s*$', line)
    if m:
        reqs[m.group(1)] = {'text': m.group(2), 'phase': m.group(3)}

cover = {r: {'unit': [], 'cypress': [], 'manual': []} for r in reqs}
unknown = []

def cite(layer, ids, where):
    for i in ids:
        if i in cover:
            if where not in cover[i][layer]:
                cover[i][layer].append(where)
        else:
            unknown.append((layer, i, where))

for f in sorted(UNIT.rglob('*Test.java')):
    src = f.read_text(encoding='utf-8')
    for m in re.finditer(r'@DisplayName\("([^"]*)"\)\s*void\s+(\w+)', src):
        cite('unit', ID.findall(m.group(1)), f'{f.stem}.{m.group(2)}')

# it(...), or now(...)/later(...) in a gate that runs in two phases of the clock (mkt-2d)
for f in sorted(CY.glob('*.cy.js')):
    for m in re.finditer(r"\b(?:it|now|later)\(\s*['`](MKT-[\w-]+?)\s((?:\[MKT-R[\d.]+\]\s*)+)", f.read_text(encoding='utf-8')):
        cite('cypress', ID.findall(m.group(2)), m.group(1))

manual = json.loads((HERE / 'manual-cases.json').read_text(encoding='utf-8'))['cases']
for c in manual:
    cite('manual', c['reqs'], c['id'])

def phase_key(p):
    d = re.findall(r'\d', p)
    return int(d[0]) if d else 9

rows, gaps = [], []
for r, v in sorted(reqs.items(), key=lambda kv: [int(x) for x in kv[0][5:].split('.')]):
    c = cover[r]
    if not (c['unit'] or c['cypress'] or c['manual']):
        gaps.append(r)
    rows.append((r, v['phase'], c))

tot = len(reqs)
n_unit = sum(1 for _, _, c in rows if c['unit'])
n_cy = sum(1 for _, _, c in rows if c['cypress'])
n_man = sum(1 for _, _, c in rows if c['manual'])
n_any = tot - len(gaps)
n_auto = sum(1 for _, _, c in rows if c['unit'] or c['cypress'])
by_phase = {}
for r, p, c in rows:
    b = by_phase.setdefault(p, [0, 0])
    b[0] += 1
    b[1] += 1 if (c['unit'] or c['cypress']) else 0

out = []
out.append(f'**Computed {len(reqs)} requirements** · any test **{n_any}/{tot}** · unit (executed) **{n_unit}** · '
           f'Cypress (written, phase-gated) **{n_cy}** · automated (unit or Cypress) **{n_auto}/{tot}** · '
           f'manual **{n_man}/{tot}** · unknown ids cited **{len(unknown)}**')
out.append('')
out.append('| Phase | Requirements | With an automated case |')
out.append('|---|---|---|')
for p in sorted(by_phase, key=phase_key):
    out.append(f'| {p} | {by_phase[p][0]} | {by_phase[p][1]} |')
out.append('')
out.append('| Req | Ph | Unit (`mvn test`, executed) | Cypress (gate) | Manual |')
out.append('|---|---|---|---|---|')
for r, p, c in rows:
    fmt = lambda xs: '<br>'.join(xs) if xs else '—'
    out.append(f'| {r} | {p} | {fmt(c["unit"])} | {fmt(c["cypress"])} | {fmt(c["manual"])} |')
block = '\n'.join(out)

plan = PLAN.read_text(encoding='utf-8')
start, end = '<!-- RTM:BEGIN (generated by docs/marketplace/rtm.py — do not edit by hand) -->', '<!-- RTM:END -->'
if start in plan and end in plan:
    plan = plan[:plan.index(start) + len(start)] + '\n' + block + '\n' + plan[plan.index(end):]
    PLAN.write_text(plan, encoding='utf-8')

(HERE / 'rtm.json').write_text(json.dumps({'total': tot, 'anyTest': n_any, 'unit': n_unit, 'cypress': n_cy,
    'automated': n_auto, 'manual': n_man, 'gaps': gaps, 'unknown': unknown,
    'rows': [{'req': r, 'phase': p, 'text': reqs[r]['text'], **c} for r, p, c in rows]}, indent=1,
    ensure_ascii=False), encoding='utf-8')

# ── the manual walk as Markdown, from the same JSON the published page renders ─────────────────────────────
md = ['# Manual test cases: multi-seller marketplace (MKT)', '',
      '**Generated** from [`marketplace/manual-cases.json`](marketplace/manual-cases.json) by `marketplace/rtm.py`. '
      'Edit the JSON, not this file. The same cases are on the [published manual-testing page](https://claude.ai/artifact/U1FyPcwSxYsg4pGLsyFzq8), where testers record '
      'Pass / Fail / Blocked. Per GATE-RUNBOOK §6 they also belong in the product Test Book.', '',
      '**How to read a case.** Who, what must be true before, then numbered steps — each one action and the result that '
      'proves it — and a cleanup that puts the test data back. Cases of built slices are RECORDED: '
      '`cypress/e2e/marketplace/walk/mkt-walk.cy.js` performs every step on a live stack, asserts its expected result and '
      'captures the screen (the pictures are on the published page). Cases of slices not built yet are written from the '
      'design. ⚠ marks a case that guards a known trap: repeat it after any nearby change.', '',
      '| Account | Password | Plays |', '|---|---|---|',
      '| `owner.business@myplus.com` | `Demo@2025!` | Seller A (retail counter; admin./user. ladder in the same org) |',
      '| `owner.mobile@myplus.com` | `Demo@2025!` | Seller B (mobile shop: the second seller of the same phone) |',
      '| `owner.audit@myplus.com` | `Demo@2025!` | a shop that has never applied (reset with walk-reset.sql) |',
      '| `owner.pesticide@myplus.com` | `Demo@2025!` | a shop MaxTheService never entitled |',
      '| `owner.pharma@myplus.com` | `Demo@2025!` | a pharmacy (prescription control on) |',
      '| `user.business@myplus.com` | `Demo@2025!` | a user-tier member of Seller A |',
      '| `admin@myplus.com` | `Admin@2025!` | MaxTheService operator |', '']
section = None
for c in manual:
    if c['slice'] != section:
        section = c['slice']
        md += ['', f'## {section}', '']
    how = (f"recorded {c['recordedAt'][:16].replace('T', ' ')} UTC" if c.get('evidence') == 'recorded'
           else 'written from the design — not built yet')
    md += [f"### {c['id']} {'⚠ ' if c.get('warn') else ''}{c['title']}", '',
           f"**Who:** {c['persona']}  ", f"**Before:** {c['pre'] or '—'}  ", f"**Covers:** {', '.join(c['reqs'])}  ",
           f"**Evidence:** {how}" + (f"  \n**Automated by:** {', '.join(c['auto'])}" if c.get('auto') else ''), '',
           '| # | Do this | Expect |', '|---|---|---|']
    cell = lambda s: s.replace('|', '\\|').replace('\n', ' ')
    for s in c['steps']:
        flow = f" *(screen not available: {cell(s['flow'])})*" if s.get('flow') else ''
        md.append(f"| {s['n']} | {cell(s['do'])}{flow} | {cell(s['expect'])} |")
    for s in c.get('cleanup', []):
        md.append(f"| C{s['n']} | {cell(s['do'])} | {cell(s['expect'])} |")
    for f in c.get('found', []):
        md += ['', f'> **Found by the walk:** {f}']
    md.append('')
(HERE.parent / 'manual-test-marketplace-multiseller.md').write_text('\n'.join(md) + '\n', encoding='utf-8')

print(block.splitlines()[0])
if unknown:
    print('UNKNOWN ids cited:', unknown)
if gaps:
    print('UNCOVERED:', gaps)
sys.exit(1 if (gaps or unknown) else 0)
